name: Deploy BASIC WEB (Remote)
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy BASIC WEB (Remote)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key:  ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /var/www/html/ejemplo

            sudo git pull
